# coding: utf-8

# flake8: noqa

"""
    DMI Open Data API - Forecast data

    <h2>Free access to the Danish Meteorological Institutes data.  <img style=\"float: right; max-width: 6%;\" src='https://www.dmi.dk/fileadmin/templates/img/logo.png'></img></h2>                    <p>The services provided by this API require authentication and an authentication key is mandatory.<br/>In order to retrieve data it is necessary to register as user. Read more here: <a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/Authentication\">Authentication</a></p>                    <p><a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/APIs/Forecast_Data_STAC-API\">Information about the Forecast Data service</a></p>                    <p>This service follows the standard for STAC API - Features as described in <a href=\"https://api.stacspec.org/v1.0.0-beta.4/core/\">STAC API - Core</a></p>

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from dmi_open_data.forecastdata.api.capabilities_api import CapabilitiesApi
from dmi_open_data.forecastdata.api.dkss_forecast_data_grib_files_api import DKSSForecastDataGRIBFilesApi
from dmi_open_data.forecastdata.api.download_forecast_files_api import DownloadForecastFilesApi
from dmi_open_data.forecastdata.api.harmonie_forecast_data_grib_files_api import HARMONIEForecastDataGRIBFilesApi
from dmi_open_data.forecastdata.api.wam_forecast_data_grib_files_api import WAMForecastDataGRIBFilesApi

# import ApiClient
from dmi_open_data.forecastdata.api_response import ApiResponse
from dmi_open_data.forecastdata.api_client import ApiClient
from dmi_open_data.forecastdata.configuration import Configuration
from dmi_open_data.forecastdata.exceptions import OpenApiException
from dmi_open_data.forecastdata.exceptions import ApiTypeError
from dmi_open_data.forecastdata.exceptions import ApiValueError
from dmi_open_data.forecastdata.exceptions import ApiKeyError
from dmi_open_data.forecastdata.exceptions import ApiAttributeError
from dmi_open_data.forecastdata.exceptions import ApiException

# import models into sdk package
from dmi_open_data.forecastdata.models.collection import Collection
from dmi_open_data.forecastdata.models.collections import Collections
from dmi_open_data.forecastdata.models.conformance import Conformance
from dmi_open_data.forecastdata.models.extent import Extent
from dmi_open_data.forecastdata.models.feature import Feature
from dmi_open_data.forecastdata.models.feature_collection import FeatureCollection
from dmi_open_data.forecastdata.models.geometry import Geometry
from dmi_open_data.forecastdata.models.landing_page import LandingPage
from dmi_open_data.forecastdata.models.link import Link
from dmi_open_data.forecastdata.models.spatial import Spatial
from dmi_open_data.forecastdata.models.temporal import Temporal
