# flake8: noqa

# import apis into api package
from dmi_open_data.climatedata.api.capabilities_api import CapabilitiesApi
from dmi_open_data.climatedata.api.climate_data10km_grid_values_api import ClimateData10kmGridValuesApi
from dmi_open_data.climatedata.api.climate_data20km_grid_values_api import ClimateData20kmGridValuesApi
from dmi_open_data.climatedata.api.climate_data_country_values_api import ClimateDataCountryValuesApi
from dmi_open_data.climatedata.api.climate_data_municipality_values_api import ClimateDataMunicipalityValuesApi
from dmi_open_data.climatedata.api.climate_data_station_values_api import ClimateDataStationValuesApi
from dmi_open_data.climatedata.api.climate_stations_station_data_api import ClimateStationsStationDataApi

