# coding: utf-8

# flake8: noqa
"""
    DMI Open Data API - Climate observation

    <h2>Free access to the Danish Meteorological Institutes data.  <img style=\"float: right; max-width: 6%;\" src='https://www.dmi.dk/fileadmin/templates/img/logo.png'></img></h2>                    <p>The services provided by this API require authentication and an authentication key is mandatory.<br/>In order to retrieve data it is necessary to register as user. Read more here: <a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/Authentication\">Authentication</a></p>                    <p><a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/APIs/Climate_Data_API\">Information about the Climate Data service</a></p>                    <p>This service follows the standard for OGC API Features as described in <a href=\"https://docs.opengeospatial.org/is/17-069r3/17-069r3.html\">OGC API - Features - Part 1: Core</a></p>

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from dmi_open_data.climatedata.models.collection import Collection
from dmi_open_data.climatedata.models.collections import Collections
from dmi_open_data.climatedata.models.conformance import Conformance
from dmi_open_data.climatedata.models.extent import Extent
from dmi_open_data.climatedata.models.feature import Feature
from dmi_open_data.climatedata.models.feature_collection import FeatureCollection
from dmi_open_data.climatedata.models.geometry import Geometry
from dmi_open_data.climatedata.models.landing_page import LandingPage
from dmi_open_data.climatedata.models.link import Link
from dmi_open_data.climatedata.models.spatial import Spatial
from dmi_open_data.climatedata.models.temporal import Temporal
