# coding: utf-8

# flake8: noqa

"""
    DMI Open Data API - Climate observation

    <h2>Free access to the Danish Meteorological Institutes data.  <img style=\"float: right; max-width: 6%;\" src='https://www.dmi.dk/fileadmin/templates/img/logo.png'></img></h2>                    <p>The services provided by this API require authentication and an authentication key is mandatory.<br/>In order to retrieve data it is necessary to register as user. Read more here: <a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/Authentication\">Authentication</a></p>                    <p><a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/APIs/Climate_Data_API\">Information about the Climate Data service</a></p>                    <p>This service follows the standard for OGC API Features as described in <a href=\"https://docs.opengeospatial.org/is/17-069r3/17-069r3.html\">OGC API - Features - Part 1: Core</a></p>

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from dmi_open_data.climatedata.api.capabilities_api import CapabilitiesApi
from dmi_open_data.climatedata.api.climate_data10km_grid_values_api import ClimateData10kmGridValuesApi
from dmi_open_data.climatedata.api.climate_data20km_grid_values_api import ClimateData20kmGridValuesApi
from dmi_open_data.climatedata.api.climate_data_country_values_api import ClimateDataCountryValuesApi
from dmi_open_data.climatedata.api.climate_data_municipality_values_api import ClimateDataMunicipalityValuesApi
from dmi_open_data.climatedata.api.climate_data_station_values_api import ClimateDataStationValuesApi
from dmi_open_data.climatedata.api.climate_stations_station_data_api import ClimateStationsStationDataApi

# import ApiClient
from dmi_open_data.climatedata.api_response import ApiResponse
from dmi_open_data.climatedata.api_client import ApiClient
from dmi_open_data.climatedata.configuration import Configuration
from dmi_open_data.climatedata.exceptions import OpenApiException
from dmi_open_data.climatedata.exceptions import ApiTypeError
from dmi_open_data.climatedata.exceptions import ApiValueError
from dmi_open_data.climatedata.exceptions import ApiKeyError
from dmi_open_data.climatedata.exceptions import ApiAttributeError
from dmi_open_data.climatedata.exceptions import ApiException

# import models into sdk package
from dmi_open_data.climatedata.models.collection import Collection
from dmi_open_data.climatedata.models.collections import Collections
from dmi_open_data.climatedata.models.conformance import Conformance
from dmi_open_data.climatedata.models.extent import Extent
from dmi_open_data.climatedata.models.feature import Feature
from dmi_open_data.climatedata.models.feature_collection import FeatureCollection
from dmi_open_data.climatedata.models.geometry import Geometry
from dmi_open_data.climatedata.models.landing_page import LandingPage
from dmi_open_data.climatedata.models.link import Link
from dmi_open_data.climatedata.models.spatial import Spatial
from dmi_open_data.climatedata.models.temporal import Temporal
