# coding: utf-8

# flake8: noqa

"""
    DMI Open Data API - Radar data

    <h2>Free access to the Danish Meteorological Institutes data.  <img style=\"float: right; max-width: 6%;\" src='https://www.dmi.dk/fileadmin/templates/img/logo.png'></img></h2>                    <p>The services provided by this API require authentication and an authentication key is mandatory.<br/>In order to retrieve data it is necessary to register as user. Read more here: <a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/Authentication\">Authentication</a></p>                    <p><a style=\"text-decoration: none;\" href=\"https://opendatadocs.dmi.govcloud.dk/en/APIs/Radar_Data_API\">Information about the Radar Data service</a></p>                    <p>This service follows the standard for STAC API - Features as described in <a href=\"https://api.stacspec.org/v1.0.0-beta.4/core/\">STAC API - Core</a></p>

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from dmi_open_data.radardata.api.capabilities_api import CapabilitiesApi
from dmi_open_data.radardata.api.download_radar_files_api import DownloadRadarFilesApi
from dmi_open_data.radardata.api.radar_data_composite_files_api import RadarDataCompositeFilesApi
from dmi_open_data.radardata.api.radar_data_pseudo_cappi_files_api import RadarDataPseudoCAPPIFilesApi
from dmi_open_data.radardata.api.radar_data_volume_files_api import RadarDataVolumeFilesApi

# import ApiClient
from dmi_open_data.radardata.api_response import ApiResponse
from dmi_open_data.radardata.api_client import ApiClient
from dmi_open_data.radardata.configuration import Configuration
from dmi_open_data.radardata.exceptions import OpenApiException
from dmi_open_data.radardata.exceptions import ApiTypeError
from dmi_open_data.radardata.exceptions import ApiValueError
from dmi_open_data.radardata.exceptions import ApiKeyError
from dmi_open_data.radardata.exceptions import ApiAttributeError
from dmi_open_data.radardata.exceptions import ApiException

# import models into sdk package
from dmi_open_data.radardata.models.collection import Collection
from dmi_open_data.radardata.models.collections import Collections
from dmi_open_data.radardata.models.conformance import Conformance
from dmi_open_data.radardata.models.extent import Extent
from dmi_open_data.radardata.models.feature import Feature
from dmi_open_data.radardata.models.feature_collection import FeatureCollection
from dmi_open_data.radardata.models.geometry import Geometry
from dmi_open_data.radardata.models.landing_page import LandingPage
from dmi_open_data.radardata.models.link import Link
from dmi_open_data.radardata.models.spatial import Spatial
from dmi_open_data.radardata.models.temporal import Temporal
